### ISSUE TITLE
go and delve version mismatch

### ISSUE THREAD

**Issue by tristanbeedell** [cachix/devenv-nixpkgs#10]
with

```devenv.yaml
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
```

trying to use the go debugger in vscode:

![image](https://github.com/user-attachments/assets/595ad6b1-6548-432e-8083-c4d0860160cf)

swap nixpkgs out for `github:nixos/nixpkgs/nixos-unstable` and it works as expected.

**Comment by sandydoo** [comment]
Do you have another version of go installed? I imagine you might have one version in `GOROOT` and another in the `PATH`.

If that's the underlying issue, then you'll eventually run into this again.

**Comment by domenkozar** [comment]
We switched to unstable1
